workflows:
  maui-ios-development:
    name: Dotnet MAUI iOS Development
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.xianyu.zz
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET_BIN: $CM_BUILD_DIR/dotnet/dotnet
    scripts:
      - name: Install dotnet sdk
        script: |
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir $DOTNET_PATH --channel 8.0

      - name: Install MAUI and iOS workloads
        script: |
          $DOTNET_BIN nuget locals all --clear 
          $DOTNET_BIN workload install ios maui --source https://aka.ms/dotnet8/nuget/index.json --source https://api.nuget.org/v3/index.json      

      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/src/WeatherTwentyOne/Platforms/iOS/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST

#      - name: Set build version and build the iOS app
#        script: |
#          CERT_NAME=$(keychain list-certificates | jq -r '.[] | .common_name')
#          PROFILE_NAME=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" -execdir sh -c '/usr/libexec/PlistBuddy -c "print :Name" /dev/stdin <<< $(security cms -D -i {})' \;)
#
#          find . -name "package.json" -exec rm -rf {} +
#          find . -name "package-lock.json" -exec rm -rf {} +
#
#          $DOTNET_BIN publish -f net8.0-ios \
#            -c Release \
#            -p:BuildIpa=True \
#            -p:ApplicationDisplayVersion="1.0.0" \
#            -p:ApplicationVersion=1 \
#            -p:RuntimeIdentifier=ios-arm64 \
#            -p:CodesignKey="$CERT_NAME" \
#            -p:CodesignProvision="$PROFILE_NAME" \
#            -o /Users/builder/artifacts/ios

      - name: Build macOS (Mac Catalyst) app
        script: |
          $DOTNET_BIN workload install maccatalyst --source https://aka.ms/dotnet8/nuget/index.json --source https://api.nuget.org/v3/index.json

          $DOTNET_BIN publish -f net8.0-maccatalyst \
            -c Release \
            -p:ApplicationDisplayVersion="1.0.0" \
            -p:ApplicationVersion=1 \
            -o /Users/builder/artifacts/macos

    artifacts:
#      - /Users/builder/artifacts/ios/*.ipa
      - /Users/builder/artifacts/macos/*.app
    publishing:
      email:
        recipients:
          - truereality@foxmail.com
        notify:
          success: true
          failure: false
