workflows:
  ios-adhoc:
    name: iOS Ad Hoc Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET_BIN: $CM_BUILD_DIR/dotnet/dotnet
    scripts:
      - name: Decode and save signing files
        script: |
          # 解码 .p12 文件
          echo $IOS_P12_BASE64 | base64 --decode > ios_cert.p12
          
          # 解码 .mobileprovision 文件
          echo $IOS_PROVISION_BASE64 | base64 --decode > ios.mobileprovision
          
          # 安装证书
          security import ios_cert.p12 -P $IOS_P12_PASSWORD -A -T /usr/bin/codesign
          
          # 安装描述文件
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mv ios.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Install .NET SDK
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir $DOTNET_PATH

      - name: Install MAUI and iOS workloads
        script: |
          $DOTNET_BIN nuget locals all --clear 
          $DOTNET_BIN workload install ios maui \
            --source https://aka.ms/dotnet6/nuget/index.json \
            --source https://api.nuget.org/v3/index.json

      - name: Build the Ad Hoc app
        script: |
          cd src
          $DOTNET_BIN publish -f net6.0-ios \
            -c Release \
            -p:BuildIpa=True \
            -p:RuntimeIdentifier=ios-arm64 \
            -p:CodesignKey="ios_cert.p12" \
            -p:CodesignProvision="ios.mobileprovision" \
            -p:ApplicationDisplayVersion="1.0.0" \
            -p:ApplicationVersion=1 \
            -o ../artifacts

    artifacts:
      - ./artifacts/*.ipa
